USE [master]
GO
/****** Object:  Database [dotazioni2021]    Script Date: 03/24/2021 16:05:32 ******/
CREATE DATABASE [dotazioni2021] ON  PRIMARY 
( NAME = N'dotazioni2021', FILENAME = N'C:\root\dataSql\dat\dotazioni2021.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dotazioni2021_log', FILENAME = N'C:\root\dataSql\log\dotazioni2021_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [dotazioni2021] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dotazioni2021].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dotazioni2021] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [dotazioni2021] SET ANSI_NULLS OFF
GO
ALTER DATABASE [dotazioni2021] SET ANSI_PADDING OFF
GO
ALTER DATABASE [dotazioni2021] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [dotazioni2021] SET ARITHABORT OFF
GO
ALTER DATABASE [dotazioni2021] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [dotazioni2021] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [dotazioni2021] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [dotazioni2021] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [dotazioni2021] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [dotazioni2021] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [dotazioni2021] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [dotazioni2021] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [dotazioni2021] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [dotazioni2021] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [dotazioni2021] SET  DISABLE_BROKER
GO
ALTER DATABASE [dotazioni2021] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [dotazioni2021] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [dotazioni2021] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [dotazioni2021] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [dotazioni2021] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [dotazioni2021] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [dotazioni2021] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [dotazioni2021] SET  READ_WRITE
GO
ALTER DATABASE [dotazioni2021] SET RECOVERY SIMPLE
GO
ALTER DATABASE [dotazioni2021] SET  MULTI_USER
GO
ALTER DATABASE [dotazioni2021] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [dotazioni2021] SET DB_CHAINING OFF
GO
